//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zainab
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMess
    {
        public tblMess()
        {
            this.tblMessRecords = new HashSet<tblMessRecord>();
        }
    
        public int Id { get; set; }
        public string Day { get; set; }
        public string Dish { get; set; }
        public Nullable<int> Rate { get; set; }
    
        public virtual ICollection<tblMessRecord> tblMessRecords { get; set; }
    }
}
