//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zainab
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbZainabEntities1 : DbContext
    {
        public dbZainabEntities1()
            : base("name=dbZainabEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tblAttendence> tblAttendences { get; set; }
        public DbSet<tblStaff> tblStaffs { get; set; }
        public DbSet<tblBookingRoom> tblBookingRooms { get; set; }
        public DbSet<tblRoom> tblRooms { get; set; }
        public DbSet<tblStudentInformation> tblStudentInformations { get; set; }
        public DbSet<tblMess> tblMesses { get; set; }
        public DbSet<tblMessRecord> tblMessRecords { get; set; }
        public DbSet<tblExpensive> tblExpensives { get; set; }
        public DbSet<tblFeeSubmission> tblFeeSubmissions { get; set; }
        public DbSet<tblMonth> tblMonths { get; set; }
        public DbSet<tblRoomType> tblRoomTypes { get; set; }
    }
}
